### POSTGRESQL CONFIGURATION ###
database-platform: &database-platform postgres
database-driver: &database-driver org.postgresql.Driver
database-dialect: &database-dialect org.hibernate.dialect.PostgreSQL95Dialect
database-schema: &database-schema shopping_management
database-url: &database-url "jdbc:postgresql://192.168.50.62:5432/shopping"
database-user: &database-user administrator
database-pass: &database-pass 123456789

server:
  port: 8080

application:
  title: Microservice Shopping Basket
  version: 0.0.1

spring:
  application:
    name: ms-shopping-basket-management
  datasource:
    platform: *database-platform
    driver-class-name: *database-driver
    url: "jdbc:postgresql://192.168.50.62:5432/shopping"
    username: administrator
    password: 123456789
    hikari:
      poolName: ShoppingManagementPool
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 15000
      maxLifetime: 30000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    currentSchema: shopping_management
    properties:
      hibernate:
        default_schema: shopping_management
        jdbc.lob.non_contextual_creation: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    baselineVersion: 0
    url: *database-url
    user: *database-user
    password: *database-pass
    schemas: *database-schema
    table: shopping_schema_version


